### ISSUE TITLE
Cant start under win10/64

### ISSUE THREAD

**Issue by strech345** [mrkeuz/vlcsync#1]
Hello,
first get a message that this might harm my pc. think because the owner of this software is not windows license.

But after accept this worning, get the error that i doenst have the right to install. After that this exe is removed.
also avira told me that this is a virus :-(

**Comment by mrkeuz** [comment]
Thanks for reporting.

Windows build it is experimental. This is first python app I have packaged. 
I will investigate this issue when I have enough time. 
Probably it needed sign app or similar.

Right now you can try next options:

1. I remember that there were some issues to run when vlcsync.exe was under `~/User/Downloads` (or similar).   So just try to move binary to i.e. `C:\vlcsync` folder. Then try again to run.

2. If that doesn't help, just try to install `vlcsync` from sources:

- Install python (with  [Add Python to PATH](https://datatofish.com/add-python-to-windows-path/) checkbox)
- Restart
- Start console (Press `Super` → type `cmd` → press `Enter`)
- Run in console: `pip3 install vlcsync`
- For start program. Run in console: `vlcsync`

Let me know if there are some issues.

Also, could you tell me what antivirus you're use?

**Comment by mrkeuz** [comment]
I have done investigation.

Issue related to `pyinstaller` "AntiVirus false positive" issues: 
 - https://github.com/pyinstaller/pyinstaller/issues/5932 
 - and similar [antivirus-false-positives](https://github.com/pyinstaller/pyinstaller/issues?q=label%3Aantivirus-false-positives+is%3Aclosed) issues.

For fix, it needs to buy MS Certificate and sign binaries. And do additional tricks.
Windows is not priority platform, so issue will NOT PLAN to fix.

For installing use `pip3` installation method, described above.
I will update README for this.

**Comment by mrkeuz** [comment]
I've added alternative way installation instructions for Widows:
https://github.com/mrkeuz/vlcsync/blob/main/docs/install.md

**Comment by strech345** [comment]
@mrkeuz thanks!
i will check it.
