### ISSUE TITLE
Feat: Synchronize Playlist Sequence

### ISSUE THREAD

**Issue by NiTOXide** [mrkeuz/vlcsync#7]
**Synchronize Playlist Sequence**

Description

Synchronize playlist position across all the players. 

First Example: a player moves to the number 2 file in the playlist, all other players move to the number 2 file in their playlist. 

Second Example: a player moves to the number 1 file in the playlist, all other players move to the number 1 file in their playlists. 

Note: The players are not using the same playlist - just sharing the file number position in the playlist. 

Potential problem: If the playlists don't have the same number of files, what should happen? 

For example, a player moves to the number 9 file in their play lists, all other players only have 8 files in their playlist? If this, then:

- Repeat the same file?
- User must ensure all playlists have the same number of files?

**Describe alternatives you've considered**
Manually advancing each player in their playlists. 

**Additional context**

**Comment by mrkeuz** [comment]
Little update, I'm almost done feature. I had to change the "main" sync algorithm for this. But still there are bugs in corner cases. 

Will prepare alpha version soon just for ability use as-is for those who are waiting and for testing. 

Related to #8 as I had to do a fairly subtle refactoring entire of the codebase.
