### ISSUE TITLE
Feat: mac support

### ISSUE THREAD

**Issue by faultyd3v** [mrkeuz/vlcsync#9]
**Describe the bug**
Enable support on mac.

**To Reproduce**
1. sudo ifconfig lo0 alias 127.0.0.42 up
2. [== 'vlc'](https://github.com/mrkeuz/vlcsync/blob/main/vlcsync/vlc_finder.py#L78)  -- on mac, it's 'VLC'
3. Presto, works on mac.

**Comment by mrkeuz** [comment]
@faultyd3v fixed in #10. I have no macOS for testing. So please test, if you will have the time. Then I will close this issue.

`pip3 install -U vlcsync==0.2.1`

Thanks!

**Comment by mrkeuz** [comment]
I'll close this issue as seems all should work. Just reopen issue if any issues.
